/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/meta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Meta */
    get: operations["meta_api_meta_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/devices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Devices */
    get: operations["get_devices_api_devices_get"];
    put?: never;
    /** Create Device */
    post: operations["create_device_api_devices_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/devices/{device_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Device */
    get: operations["get_device_api_devices__device_id__get"];
    /** Update Device */
    put: operations["update_device_api_devices__device_id__put"];
    post?: never;
    /** Delete Device */
    delete: operations["delete_device_api_devices__device_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/switches": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Switches */
    get: operations["get_switches_api_switches_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cables": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Cables */
    get: operations["get_cables_api_cables_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Cable */
    Cable: {
      /** Id */
      id: string;
      /** Cat */
      cat?: string | null;
      /** Len */
      len?: string | null;
      /** Color */
      color?: string | null;
      /** Jacket */
      jacket?: string | null;
      /** Fromdev */
      fromDev: string;
      /** Fromport */
      fromPort?: string | number | null;
      /** Todev */
      toDev: string;
      /** Toport */
      toPort?: string | number | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * Device
     * @description A stored device: create payload + its (immutable) id.
     */
    Device: {
      /** Name */
      name: string;
      /** Host */
      host: string;
      /** Ip */
      ip: string;
      /** Mac */
      mac: string;
      /**
       * Group
       * @enum {string}
       */
      group: "Infra" | "IoT" | "Media" | "Mobile" | "Computer" | "Misc";
      /** Type */
      type: string;
      /**
       * Online
       * @default false
       */
      online: boolean;
      /** Cpu */
      cpu?: string | null;
      /** Mem */
      mem?: string | null;
      /** Storage */
      storage?: string | null;
      /** Conn */
      conn?:
        | (
            | "Wired 1G"
            | "Wired 2.5G"
            | "Wired 100M"
            | "Wi-Fi 2.4 GHz"
            | "Wi-Fi 5 GHz"
            | "Wi-Fi 6 GHz"
            | "—"
          )
        | null;
      /** Ring */
      ring?: (0 | 1 | 2) | null;
      /** Idx */
      idx?: number | null;
      /** Last */
      last?: string | null;
      /** Uptime */
      uptime?: string | null;
      /** Notes */
      notes?: string | null;
      detail?: components["schemas"]["DeviceDetail"] | null;
      /** Id */
      id: string;
    };
    /**
     * DeviceCreate
     * @description Body for POST /api/devices — id is supplied by the client (kebab-case).
     */
    DeviceCreate: {
      /** Name */
      name: string;
      /** Host */
      host: string;
      /** Ip */
      ip: string;
      /** Mac */
      mac: string;
      /**
       * Group
       * @enum {string}
       */
      group: "Infra" | "IoT" | "Media" | "Mobile" | "Computer" | "Misc";
      /** Type */
      type: string;
      /**
       * Online
       * @default false
       */
      online: boolean;
      /** Cpu */
      cpu?: string | null;
      /** Mem */
      mem?: string | null;
      /** Storage */
      storage?: string | null;
      /** Conn */
      conn?:
        | (
            | "Wired 1G"
            | "Wired 2.5G"
            | "Wired 100M"
            | "Wi-Fi 2.4 GHz"
            | "Wi-Fi 5 GHz"
            | "Wi-Fi 6 GHz"
            | "—"
          )
        | null;
      /** Ring */
      ring?: (0 | 1 | 2) | null;
      /** Idx */
      idx?: number | null;
      /** Last */
      last?: string | null;
      /** Uptime */
      uptime?: string | null;
      /** Notes */
      notes?: string | null;
      detail?: components["schemas"]["DeviceDetail"] | null;
      /** Id */
      id: string;
    };
    /**
     * DeviceDetail
     * @description Detail-view-only payload (spec §3.3). All fields optional / nullable.
     */
    DeviceDetail: {
      net?: components["schemas"]["NetInfo"] | null;
      hw?: components["schemas"]["HwInfo"] | null;
      metrics?: components["schemas"]["Metrics"] | null;
      /** Services */
      services?: components["schemas"]["Service"][] | null;
      storage?: components["schemas"]["StorageInfo"] | null;
      /** Hist7 */
      hist7?: number[] | null;
      own?: components["schemas"]["Ownership"] | null;
    };
    /**
     * DeviceUpdate
     * @description Body for PUT /api/devices/{id} — id is immutable, taken from the path.
     */
    DeviceUpdate: {
      /** Name */
      name: string;
      /** Host */
      host: string;
      /** Ip */
      ip: string;
      /** Mac */
      mac: string;
      /**
       * Group
       * @enum {string}
       */
      group: "Infra" | "IoT" | "Media" | "Mobile" | "Computer" | "Misc";
      /** Type */
      type: string;
      /**
       * Online
       * @default false
       */
      online: boolean;
      /** Cpu */
      cpu?: string | null;
      /** Mem */
      mem?: string | null;
      /** Storage */
      storage?: string | null;
      /** Conn */
      conn?:
        | (
            | "Wired 1G"
            | "Wired 2.5G"
            | "Wired 100M"
            | "Wi-Fi 2.4 GHz"
            | "Wi-Fi 5 GHz"
            | "Wi-Fi 6 GHz"
            | "—"
          )
        | null;
      /** Ring */
      ring?: (0 | 1 | 2) | null;
      /** Idx */
      idx?: number | null;
      /** Last */
      last?: string | null;
      /** Uptime */
      uptime?: string | null;
      /** Notes */
      notes?: string | null;
      detail?: components["schemas"]["DeviceDetail"] | null;
    };
    /** Drive */
    Drive: {
      /** Nm */
      nm: string;
      /** Md */
      md?: string | null;
      /** Size */
      size?: string | null;
      /**
       * Pct
       * @default 0
       */
      pct: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HwInfo */
    HwInfo: {
      /** Cpu Full */
      cpu_full?: string | null;
      /** Arch */
      arch?: string | null;
      /** Mem Full */
      mem_full?: string | null;
      /** Chassis */
      chassis?: string | null;
      /** Bios */
      bios?: string | null;
    };
    /** Meta */
    Meta: {
      /** Total */
      total: number;
      /** Online */
      online: number;
      /** Offline */
      offline: number;
      /** Updated At */
      updated_at?: string | null;
    };
    /** Metrics */
    Metrics: {
      /** Cpu Pct */
      cpu_pct?: number | null;
      /** Cpu Series */
      cpu_series?: number[] | null;
      /** Mem Pct */
      mem_pct?: number | null;
      /** Mem Series */
      mem_series?: number[] | null;
      /** Net In */
      net_in?: number | null;
      /** Net Out */
      net_out?: number | null;
      /** Net In Series */
      net_in_series?: number[] | null;
      /** Temp */
      temp?: number | null;
    };
    /** NetInfo */
    NetInfo: {
      /** Ipv4 */
      ipv4?: string | null;
      /** Ipv6 */
      ipv6?: string | null;
      /** Gateway */
      gateway?: string | null;
      /** Dns */
      dns?: string | null;
      /** Dhcp */
      dhcp?: string | null;
      /** Vlan */
      vlan?: string | null;
      /** Rssi */
      rssi?: string | null;
    };
    /** Ownership */
    Ownership: {
      /** Manufacturer */
      manufacturer?: string | null;
      /** Model */
      model?: string | null;
      /** Purchased */
      purchased?: string | null;
      /** Price */
      price?: string | null;
      /** Warranty */
      warranty?: string | null;
      /** Location */
      location?: string | null;
      /** Tags */
      tags?: string[] | null;
    };
    /** PortSlot */
    PortSlot: {
      /** Device */
      device: string;
      /** Cable */
      cable?: string | null;
      /** Role */
      role?: ("uplink" | "downlink") | null;
    };
    /** Service */
    Service: {
      /** Port */
      port: number;
      /**
       * Proto
       * @default tcp
       */
      proto: string;
      /**
       * Svc
       * @default
       */
      svc: string;
      /**
       * Banner
       * @default
       */
      banner: string;
    };
    /** StorageInfo */
    StorageInfo: {
      /** Drives */
      drives?: components["schemas"]["Drive"][] | null;
      /** Pool */
      pool?: string | null;
      /** Health */
      health?: string | null;
    };
    /** Switch */
    Switch: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Model */
      model?: string | null;
      /**
       * Type
       * @default switch
       * @enum {string}
       */
      type: "switch" | "hub";
      /** Location */
      location?: string | null;
      /** Portcount */
      portCount?: number | null;
      /** Speed */
      speed?: string | null;
      /** Managed */
      managed?: boolean | null;
      /**
       * Online
       * @default true
       */
      online: boolean;
      /** Notes */
      notes?: string | null;
      /** Radio */
      radio?: string | null;
      /**
       * Portmap
       * @default {}
       */
      portMap: {
        [key: string]: components["schemas"]["PortSlot"] | null;
      };
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  meta_api_meta_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Meta"];
        };
      };
    };
  };
  get_devices_api_devices_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Device"][];
        };
      };
    };
  };
  create_device_api_devices_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeviceCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Device"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_device_api_devices__device_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        device_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Device"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_device_api_devices__device_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        device_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeviceUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Device"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_device_api_devices__device_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        device_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_switches_api_switches_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Switch"][];
        };
      };
    };
  };
  get_cables_api_cables_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Cable"][];
        };
      };
    };
  };
}
