import { describe, it, expectTypeOf } from "vitest";
import type { components } from "./api-schema";
import type { Cable, Device, DeviceDetail, Meta, ReachabilityHistory, Switch } from "../types";

// Drift guard between the hand-written domain types (types.ts) and the
// OpenAPI-generated schema (api-schema.ts, regenerated by the CI `schema` job).
//
// We assert the *forward* direction — every value the app constructs is a valid
// instance of the backend contract. The reverse is intentionally not asserted:
// the app models an absent field as `undefined`, while the generated schema also
// permits `null`, so the two are compatible only one way.
//
// Because tsconfig `include` covers src/**, these assertions are type-checked by
// `tsc --noEmit` (the build step), not just by vitest — so if the backend
// contract changes and types.ts isn't updated to match, the build fails here
// instead of the drift going unnoticed (#158).
describe("types.ts conforms to the generated OpenAPI schema", () => {
  it("Device is a valid schema Device", () => {
    expectTypeOf<Device>().toMatchTypeOf<components["schemas"]["Device"]>();
  });

  it("DeviceDetail is a valid schema DeviceDetail", () => {
    expectTypeOf<DeviceDetail>().toMatchTypeOf<components["schemas"]["DeviceDetail"]>();
  });

  it("Switch is a valid schema Switch", () => {
    expectTypeOf<Switch>().toMatchTypeOf<components["schemas"]["Switch"]>();
  });

  it("Cable is a valid schema Cable", () => {
    expectTypeOf<Cable>().toMatchTypeOf<components["schemas"]["Cable"]>();
  });

  it("Meta is a valid schema Meta", () => {
    expectTypeOf<Meta>().toMatchTypeOf<components["schemas"]["Meta"]>();
  });

  it("ReachabilityHistory is a valid schema ReachabilityHistory", () => {
    expectTypeOf<ReachabilityHistory>().toMatchTypeOf<
      components["schemas"]["ReachabilityHistory"]
    >();
  });
});
